apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
           secertKeyRef:
             name: secret
             password: mongo-user
        
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
           secertKeyRef:
             name: secret
             password: mongo-password

        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
           configMapKeyRef:
             name: mongo-config
             password: mongo-service
        ports:
        - containerPort: 8081


---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30007